#logging:
#  level:

spring:
  rsocket:
    server:
      port: ${SENSOR_SERVER_PORT:7000}
      transport: websocket
      mapping-path: /rsocket
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

server:
  port: 8000

management:
  server:
    port: 8001
  endpoints:
    web:
      exposure:
        include: "metrics"
