version: "3.9"
services:
  sensor-server:
    build: reactive-server
    ports:
      - "7000:7000"
      - "8000:8000"
      - "8001:8001"
    environment:
      - SENSOR_SERVER_PORT=7000
      - JAVA_TOOL_OPTIONS=-Dlogging.level.pd.sensor\=debug

  web:
    build: reactive-web
    ports:
      - "3000:80"
    depends_on:
      - sensor-server
    environment:
      - SENSOR_SERVER_PORT=7000

  device-1:
    build: reactive-device
    depends_on:
      - sensor-server
    environment:
      - SENSOR_DEVICE_NAME=room
      - SENSOR_SERVER_HOST=sensor-server
      - SENSOR_SERVER_PORT=7000
#      - JAVA_TOOL_OPTIONS=-Dlogging.level.pd.sensor\=debug
  device-2:
    build: reactive-device
    depends_on:
      - sensor-server
    environment:
      - SENSOR_DEVICE_NAME=backyard
      - SENSOR_SERVER_HOST=sensor-server
      - SENSOR_SERVER_PORT=7000
#      - JAVA_TOOL_OPTIONS=-Dlogging.level.pd.sensor\=debug
  device-3:
    build: reactive-device
    depends_on:
      - sensor-server
    environment:
      - SENSOR_DEVICE_NAME=garage
      - SENSOR_SERVER_HOST=sensor-server
      - SENSOR_SERVER_PORT=7000
#      - JAVA_TOOL_OPTIONS=-Dlogging.level.pd.sensor\=debug
