#logging:
#  level:
    # prints out all executed SQL statements
    #org.springframework.r2dbc: debug

spring:
  rsocket:
    server:
      port: ${SENSOR_SERVER_PORT:7000}
      transport: websocket
      mapping-path: /rsocket

management:
  endpoints:
    web:
      exposure:
        include: "metrics"
