= reactive-web

`reactive-web` streams data from `reactive-server`, i.e. either `reactive-server-r2dbc` or `reactive-server-redis`, using RSocket over WebSockets and displays the sensor data in a chart

It's implemented using:

- create-react-app
- React for UI
- Typescript
- RSocket Websocket JS client library
- Chart.js
- Yarn

== Build

. Install npm and yarn globally, if not yet, and then all dependencies

    sudo apt install npm
    sudo npm install -g yarn
    yarn install

. Build

    yarn build

== Configuration

Env. variables:

- `SENSOR_SERVER_HOST` is the server host where `reactive-server-r2dbc` or `reactive-server-redis` is running. Default is `localhost`
- `SENSOR_SERVER_PORT` is the RSocket port of the `reactive-server`.
Default is `7000`.

== Run locally

    yarn start

Then open http://localhost:3000

== Notes

I tried to use `RSocketResumableTransport` instead of low level `RSocketWebSocketClient`, but it's not that easy to make it work. This means that if the `reactive-server` (either `r2dbc` or `redis`) gets restarted, then you have to refresh the browser page manually.