= reactive-server

This is a backend part of this project.

- `reactive-server` module is a microservice that streams data in and out from 2 kind of clients:
* an inbound stream of sensor data from IoT devices (see `reactive-device`)
* an outbound steam of the sensor data to other clients (see `reactive-web`)
* a client can be a combination of both, but not necessarily.

Implemented with:

- Spring Boot
- Spring WebFlux with Netty and Project Reactor under the hood
- Persistence: Spring Data R2DBC via r2dbc H2 driver *
- Protocol: RSocket via WebSockets
- Kotlin coroutines
- Spring Actuator

NOTE: for sensors data, one of NoSQL DBs is more suitable, but I'd like to use R2DBC in this project

== Run on local machine

    java -jar reactive-server/build/libs/reactive-server-VERSION.jar

== Spring Actuator

This module exposes an Actuator endpoint, which shows the number of messages received from devices:

    curl http://localhost:8080/actuator/metrics/sensor.inbound.count

example output:

    {"name":"sensor.inbound.count","description":null,"baseUnit":null,"measurements":[{"statistic":"COUNT","value":315.0}],"availableTags":[]}

here COUNT value should increase over time when `reactive-device` is also running and sends messages to `reactive-server`